config/routes.rb
Rails.application.routes.draw do

  
  
  root 'languages#index' 
  get 'languages' => 'languages#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :langopts
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  

  get 'languages/cpp' => 'cpp#index'
  get 'languages/java' => 'java#index'
  get 'languages/ruby' => 'ruby#index'
  get 'languages/python' => 'python#index'

  get 'languages/favorite' => 'favorites#index'
  post 'languages/favorite' => 'favorites#add'
  
  get 'about' => 'feedbacks#index'
  post 'about' => 'feedbacks#create'

  get '/users/omniauth_callbacks' => 'user#facebook'
  post 'cppquizzes/check'=>'cppquizzes#check'
  post 'pythonquizzes/check'=>'pythonquizzes#check'
  post 'javaquizzes/check'=>'javaquizzes#check'
  post 'rubyquizzes/check'=>'rubyquizzes#check'
  post 'languages' => 'languages#select'

  get 'comments/index'
  get 'comments/new'
  get 'comments/create'

  post 'languages/python' => 'python#favorite'
  post 'languages/ruby' => 'ruby#favorite'
  post 'languages/java' => 'java#favorite'
  post 'languages/cpp' => 'cpp#favorite'

  resources :cppquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :pythonquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :javaquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :rubyquizzes do
  collection do
    get :answering
    get :check
  end
  end
  
  

  

end

app/controllers/pythonquizzes_controller.rb
class PythonquizzesController < ApplicationController
  before_action :set_pythonquiz, only: [:show, :edit, :update, :destroy]

  # GET /pythonquizzes
  # GET /pythonquizzes.json
  def index
    @pythonquizzes = Pythonquiz.all
  end

  # GET /pythonquizzes/1
  # GET /pythonquizzes/1.json
  def show
  end

  # GET /pythonquizzes/new
  def new
    @pythonquiz = Pythonquiz.new
  end

  # GET /pythonquizzes/1/edit
  def edit
  end

  # POST /pythonquizzes
  # POST /pythonquizzes.json
  def create
    @pythonquiz = Pythonquiz.new(pythonquiz_params)

    respond_to do |format|
      if @pythonquiz.save
        format.html { redirect_to @pythonquiz, notice: 'Pythonquiz was successfully created.' }
        format.json { render :show, status: :created, location: @pythonquiz }
      else
        format.html { render :new }
        format.json { render json: @pythonquiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pythonquizzes/1
  # PATCH/PUT /pythonquizzes/1.json
  def update
    respond_to do |format|
      if @pythonquiz.update(pythonquiz_params)
        format.html { redirect_to @pythonquiz, notice: 'Pythonquiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @pythonquiz }
      else
        format.html { render :edit }
        format.json { render json: @pythonquiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pythonquizzes/1
  # DELETE /pythonquizzes/1.json
  def destroy
    @pythonquiz.destroy
    respond_to do |format|
      format.html { redirect_to pythonquizzes_url, notice: 'Pythonquiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answering
    @quizz = Pythonquiz.all
  end
  
  def check
    @quiz = Pythonquiz.find(params[:id])
    respond_to do |format|
      if params[:ans][0].to_i == @quiz.correctAns
      flash[:notice] = "Correct Answer"
      format.html { redirect_to answering_pythonquizzes_path}
      format.json { head :ok }
    else
      flash[:notice] = "Wrong Answer"
      format.html { redirect_to answering_pythonquizzes_path}
      format.json { head :ok }
end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pythonquiz
      @pythonquiz = Pythonquiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pythonquiz_params
      params.require(:pythonquiz).permit(:question, :ans1, :ans2, :ans3, :ans4, :correctAns)
    end
end

app/helpers/pythonquizzes_helper.rb
module PythonquizzesHelper
end

app/views/pythonquizzes/_form.html.erb
<%= form_for(@pythonquiz) do |f| %>
  <% if @pythonquiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pythonquiz.errors.count, "error") %> prohibited this pythonquiz from being saved:</h2>

      <ul>
      <% @pythonquiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :ans1 %><br>
    <%= f.text_area :ans1 %>
  </div>
  <div class="field">
    <%= f.label :ans2 %><br>
    <%= f.text_area :ans2 %>
  </div>
  <div class="field">
    <%= f.label :ans3 %><br>
    <%= f.text_area :ans3 %>
  </div>
  <div class="field">
    <%= f.label :ans4 %><br>
    <%= f.text_area :ans4 %>
  </div>
  <div class="field">
    <%= f.label :correctAns %><br>
    <%= f.number_field :correctAns %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pythonquizzes/answering.html.erb
<h1 class="text-center">Quiz on Python</h1>
<% @quizz.each do |a|%>
<b><%=h a.question%></b><br><br>
<p>
1.<%=h a.ans1%>
<p>
2.<%=h a.ans2%>
</p>
3.<%=h a.ans3%>
</p>
<p>
4.<%=h a.ans4%>
</p>
<%=form_tag(:action => "check", :id => a.id) do %>
<p>
The correct answer is number:
<%=text_field :ans ,params[:ans]%>
</p>
<p><%=submit_tag("Check", :class => 'btn btn-primary')%></p><br><br>
<%end%>
<%end%>

app/views/pythonquizzes/edit.html.erb
<h1>Editing Pythonquiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @pythonquiz %> |
<%= link_to 'Back', pythonquizzes_path %>

app/views/pythonquizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pythonquizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Ans1</th>
      <th>Ans2</th>
      <th>Ans3</th>
      <th>Ans4</th>
      <th>Correctans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pythonquizzes.each do |pythonquiz| %>
      <tr>
        <td><%= pythonquiz.question %></td>
        <td><%= pythonquiz.ans1 %></td>
        <td><%= pythonquiz.ans2 %></td>
        <td><%= pythonquiz.ans3 %></td>
        <td><%= pythonquiz.ans4 %></td>
        <td><%= pythonquiz.correctAns %></td>
        <td><%= link_to 'Show', pythonquiz %></td>
        <td><%= link_to 'Edit', edit_pythonquiz_path(pythonquiz) %></td>
        <td><%= link_to 'Destroy', pythonquiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pythonquiz', new_pythonquiz_path %>

app/views/pythonquizzes/new.html.erb
<h1>New Pythonquiz</h1>

<%= render 'form' %>

<%= link_to 'Back', pythonquizzes_path %>

app/views/pythonquizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @pythonquiz.question %>
</p>

<p>
  <strong>Ans1:</strong>
  <%= @pythonquiz.ans1 %>
</p>

<p>
  <strong>Ans2:</strong>
  <%= @pythonquiz.ans2 %>
</p>

<p>
  <strong>Ans3:</strong>
  <%= @pythonquiz.ans3 %>
</p>

<p>
  <strong>Ans4:</strong>
  <%= @pythonquiz.ans4 %>
</p>

<p>
  <strong>Correctans:</strong>
  <%= @pythonquiz.correctAns %>
</p>

<%= link_to 'Edit', edit_pythonquiz_path(@pythonquiz) %> |
<%= link_to 'Back', pythonquizzes_path %>