config/routes.rb
Rails.application.routes.draw do

  
  
  root 'languages#index' 
  get 'languages' => 'languages#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :langopts
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  

  get 'languages/cpp' => 'cpp#index'
  get 'languages/java' => 'java#index'
  get 'languages/ruby' => 'ruby#index'
  get 'languages/python' => 'python#index'

  get 'languages/favorite' => 'favorites#index'
  post 'languages/favorite' => 'favorites#add'
  
  get 'about' => 'feedbacks#index'
  post 'about' => 'feedbacks#create'

  get '/users/omniauth_callbacks' => 'user#facebook'
  post 'cppquizzes/check'=>'cppquizzes#check'
  post 'pythonquizzes/check'=>'pythonquizzes#check'
  post 'javaquizzes/check'=>'javaquizzes#check'
  post 'rubyquizzes/check'=>'rubyquizzes#check'
  post 'languages' => 'languages#select'

  get 'comments/index'
  get 'comments/new'
  get 'comments/create'

  post 'languages/python' => 'python#favorite'
  post 'languages/ruby' => 'ruby#favorite'
  post 'languages/java' => 'java#favorite'
  post 'languages/cpp' => 'cpp#favorite'

  resources :cppquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :pythonquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :javaquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :rubyquizzes do
  collection do
    get :answering
    get :check
  end
  end
  
  

  

end

app/controllers/rubyquizzes_controller.rb
class RubyquizzesController < ApplicationController
  before_action :set_rubyquiz, only: [:show, :edit, :update, :destroy]

  # GET /rubyquizzes
  # GET /rubyquizzes.json
  def index
    @rubyquizzes = Rubyquiz.all
  end

  # GET /rubyquizzes/1
  # GET /rubyquizzes/1.json
  def show
  end

  # GET /rubyquizzes/new
  def new
    @rubyquiz = Rubyquiz.new
  end

  # GET /rubyquizzes/1/edit
  def edit
  end

  # POST /rubyquizzes
  # POST /rubyquizzes.json
  def create
    @rubyquiz = Rubyquiz.new(rubyquiz_params)

    respond_to do |format|
      if @rubyquiz.save
        format.html { redirect_to @rubyquiz, notice: 'Rubyquiz was successfully created.' }
        format.json { render :show, status: :created, location: @rubyquiz }
      else
        format.html { render :new }
        format.json { render json: @rubyquiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubyquizzes/1
  # PATCH/PUT /rubyquizzes/1.json
  def update
    respond_to do |format|
      if @rubyquiz.update(rubyquiz_params)
        format.html { redirect_to @rubyquiz, notice: 'Rubyquiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @rubyquiz }
      else
        format.html { render :edit }
        format.json { render json: @rubyquiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubyquizzes/1
  # DELETE /rubyquizzes/1.json
  def destroy
    @rubyquiz.destroy
    respond_to do |format|
      format.html { redirect_to rubyquizzes_url, notice: 'Rubyquiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answering
    @quizz = Rubyquiz.all
  end
  
  def check
    @quiz = Rubyquiz.find(params[:id])
    respond_to do |format|
    if params[:ans][0].to_i == @quiz.correctAns
      flash[:notice] = "Correct Answer"
      format.html { redirect_to answering_rubyquizzes_path}
      format.json { head :ok }
    else
      flash[:notice] = "Wrong Answer"
      format.html { redirect_to answering_rubyquizzes_path}
      format.json { head :ok }

end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubyquiz
      @rubyquiz = Rubyquiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubyquiz_params
      params.require(:rubyquiz).permit(:question, :ans1, :ans2, :ans3, :ans4, :correctAns)
    end
    def authenticate
      authenticate_or_request_with_http_basic do |name,password|
      name =="rhea" && password == "rhea"
    end
  end
end

app/helpers/rubyquizzes_helper.rb
module RubyquizzesHelper
end

app/views/rubyquizzes/_form.html.erb
<%= form_for(@rubyquiz) do |f| %>
  <% if @rubyquiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubyquiz.errors.count, "error") %> prohibited this rubyquiz from being saved:</h2>

      <ul>
      <% @rubyquiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :ans1 %><br>
    <%= f.text_area :ans1 %>
  </div>
  <div class="field">
    <%= f.label :ans2 %><br>
    <%= f.text_area :ans2 %>
  </div>
  <div class="field">
    <%= f.label :ans3 %><br>
    <%= f.text_area :ans3 %>
  </div>
  <div class="field">
    <%= f.label :ans4 %><br>
    <%= f.text_area :ans4 %>
  </div>
  <div class="field">
    <%= f.label :correctAns %><br>
    <%= f.number_field :correctAns %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rubyquizzes/answering.html.erb
<h1 class='text-center'>Quiz on Ruby</h1>
<% @quizz.each do |a|%>
<b><%=h a.question%></b><br><br>
<p>
1.<%=h a.ans1%>
</p>
<p>
2.<%=h a.ans2%>
</p>
3.<%=h a.ans3%>
</p>
<p>
4.<%=h a.ans4%>
</p>
<%=form_tag(:action => "check", :id => a.id) do %>
<p>
The correct answer is number:
<%=text_field :ans ,params[:ans]%>
</p>
<p><%=submit_tag("Check", :class => 'btn btn-primary')%></p><br><br>
<%end%>
<%end%>

app/views/rubyquizzes/edit.html.erb
<h1>Editing Rubyquiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @rubyquiz %> |
<%= link_to 'Back', rubyquizzes_path %>

app/views/rubyquizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rubyquizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Ans1</th>
      <th>Ans2</th>
      <th>Ans3</th>
      <th>Ans4</th>
      <th>Correctans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rubyquizzes.each do |rubyquiz| %>
      <tr>
        <td><%= rubyquiz.question %></td>
        <td><%= rubyquiz.ans1 %></td>
        <td><%= rubyquiz.ans2 %></td>
        <td><%= rubyquiz.ans3 %></td>
        <td><%= rubyquiz.ans4 %></td>
        <td><%= rubyquiz.correctAns %></td>
        <td><%= link_to 'Show', rubyquiz %></td>
        <td><%= link_to 'Edit', edit_rubyquiz_path(rubyquiz) %></td>
        <td><%= link_to 'Destroy', rubyquiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rubyquiz', new_rubyquiz_path %>

app/views/rubyquizzes/new.html.erb
<h1>New Rubyquiz</h1>

<%= render 'form' %>

<%= link_to 'Back', rubyquizzes_path %>

app/views/rubyquizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @rubyquiz.question %>
</p>

<p>
  <strong>Ans1:</strong>
  <%= @rubyquiz.ans1 %>
</p>

<p>
  <strong>Ans2:</strong>
  <%= @rubyquiz.ans2 %>
</p>

<p>
  <strong>Ans3:</strong>
  <%= @rubyquiz.ans3 %>
</p>

<p>
  <strong>Ans4:</strong>
  <%= @rubyquiz.ans4 %>
</p>

<p>
  <strong>Correctans:</strong>
  <%= @rubyquiz.correctAns %>
</p>

<%= link_to 'Edit', edit_rubyquiz_path(@rubyquiz) %> |
<%= link_to 'Back', rubyquizzes_path %>