config/routes.rb
Rails.application.routes.draw do

  
  
  root 'languages#index' 
  get 'languages' => 'languages#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :langopts
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  

  get 'languages/cpp' => 'cpp#index'
  get 'languages/java' => 'java#index'
  get 'languages/ruby' => 'ruby#index'
  get 'languages/python' => 'python#index'

  get 'languages/favorite' => 'favorites#index'
  post 'languages/favorite' => 'favorites#add'
  
  get 'about' => 'feedbacks#index'
  post 'about' => 'feedbacks#create'

  get '/users/omniauth_callbacks' => 'user#facebook'
  post 'cppquizzes/check'=>'cppquizzes#check'
  post 'pythonquizzes/check'=>'pythonquizzes#check'
  post 'javaquizzes/check'=>'javaquizzes#check'
  post 'rubyquizzes/check'=>'rubyquizzes#check'
  post 'languages' => 'languages#select'

  get 'comments/index'
  get 'comments/new'
  get 'comments/create'

  post 'languages/python' => 'python#favorite'
  post 'languages/ruby' => 'ruby#favorite'
  post 'languages/java' => 'java#favorite'
  post 'languages/cpp' => 'cpp#favorite'

  resources :cppquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :pythonquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :javaquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :rubyquizzes do
  collection do
    get :answering
    get :check
  end
  end
  
  

  

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  title      :string
#  author     :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  parent_id  :integer
#

class Comment < ActiveRecord::Base
	acts_as_tree order: 'created_at DESC'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
     @comments = Comment.hash_tree
  end

  def new
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  def create
    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
    else
      @comment = Comment.new(comment_params)
    end

    if @comment.save
      flash[:success] = 'Your comment was successfully added!'
      redirect_to comments_url
    else
      render 'new'
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:title, :body, :author)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="well">
  <h2><%= comment.title %></h2>
  <p class="text-muted">Added by <strong><%= comment.author %></strong> on
    <%= l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></p>

  <blockquote>
    <p><%= comment.body %></p>
  </blockquote>
  
  <% from_reply_form ||= nil %>
	<% unless from_reply_form %>
  <p><%= link_to 'reply', new_comment_path(comment.id) %></p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :parent_id %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control', required: true, value: current_user.email, :readonly => true %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', required: true %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<div class="jumbotron">
<div class="container">
  <h1>Join the discussion</h1>
  <p>Click the link below to start a new thread:</p>
  <p>
    <%= link_to 'Add new topic', new_comment_path, class: 'btn btn-primary btn-lg', :id => 'add_comment_link' %>
  </p>
</div>
</div>

<%= comments_tree_for @comments %>
                   

app/views/comments/new.html.erb
<h1>Add comment</h1>
<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'form' %>
                   