config/routes.rb
Rails.application.routes.draw do

  
  
  root 'languages#index' 
  get 'languages' => 'languages#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :langopts
  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  

  get 'languages/cpp' => 'cpp#index'
  get 'languages/java' => 'java#index'
  get 'languages/ruby' => 'ruby#index'
  get 'languages/python' => 'python#index'

  get 'languages/favorite' => 'favorites#index'
  post 'languages/favorite' => 'favorites#add'
  
  get 'about' => 'feedbacks#index'
  post 'about' => 'feedbacks#create'

  get '/users/omniauth_callbacks' => 'user#facebook'
  post 'cppquizzes/check'=>'cppquizzes#check'
  post 'pythonquizzes/check'=>'pythonquizzes#check'
  post 'javaquizzes/check'=>'javaquizzes#check'
  post 'rubyquizzes/check'=>'rubyquizzes#check'
  post 'languages' => 'languages#select'

  get 'comments/index'
  get 'comments/new'
  get 'comments/create'

  post 'languages/python' => 'python#favorite'
  post 'languages/ruby' => 'ruby#favorite'
  post 'languages/java' => 'java#favorite'
  post 'languages/cpp' => 'cpp#favorite'

  resources :cppquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :pythonquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :javaquizzes do
    collection do
    get :answering
    get :check
    end
  end
  resources :rubyquizzes do
  collection do
    get :answering
    get :check
  end
  end
  
  

  

end

app/controllers/javaquizzes_controller.rb
class JavaquizzesController < ApplicationController
  before_action :set_javaquiz, only: [:show, :edit, :update, :destroy]

  # GET /javaquizzes
  # GET /javaquizzes.json
  def index
    @javaquizzes = Javaquiz.all
  end

  # GET /javaquizzes/1
  # GET /javaquizzes/1.json
  def show
  end

  # GET /javaquizzes/new
  def new
    @javaquiz = Javaquiz.new
  end

  # GET /javaquizzes/1/edit
  def edit
  end

  # POST /javaquizzes
  # POST /javaquizzes.json
  def create
    @javaquiz = Javaquiz.new(javaquiz_params)

    respond_to do |format|
      if @javaquiz.save
        format.html { redirect_to @javaquiz, notice: 'Javaquiz was successfully created.' }
        format.json { render :show, status: :created, location: @javaquiz }
      else
        format.html { render :new }
        format.json { render json: @javaquiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /javaquizzes/1
  # PATCH/PUT /javaquizzes/1.json
  def update
    respond_to do |format|
      if @javaquiz.update(javaquiz_params)
        format.html { redirect_to @javaquiz, notice: 'Javaquiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @javaquiz }
      else
        format.html { render :edit }
        format.json { render json: @javaquiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /javaquizzes/1
  # DELETE /javaquizzes/1.json
  def destroy
    @javaquiz.destroy
    respond_to do |format|
      format.html { redirect_to javaquizzes_url, notice: 'Javaquiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answering
    @quizz = Javaquiz.all
  end
  
  def check
    @quiz = Javaquiz.find(params[:id])
    respond_to do |format|
      if params[:ans][0].to_i == @quiz.correctAns
      flash[:notice] = "Correct Answer"
      format.html { redirect_to answering_javaquizzes_path}
      format.json { head :ok }
    else
      flash[:notice] = "Wrong Answer"
      format.html { redirect_to answering_javaquizzes_path}
      format.json { head :ok }
end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_javaquiz
      @javaquiz = Javaquiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def javaquiz_params
      params.require(:javaquiz).permit(:question, :ans1, :ans2, :ans3, :ans4, :correctAns)
    end
end

app/helpers/javaquizzes_helper.rb
module JavaquizzesHelper
end

app/views/javaquizzes/_form.html.erb
<%= form_for(@javaquiz) do |f| %>
  <% if @javaquiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@javaquiz.errors.count, "error") %> prohibited this javaquiz from being saved:</h2>

      <ul>
      <% @javaquiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :ans1 %><br>
    <%= f.text_area :ans1 %>
  </div>
  <div class="field">
    <%= f.label :ans2 %><br>
    <%= f.text_area :ans2 %>
  </div>
  <div class="field">
    <%= f.label :ans3 %><br>
    <%= f.text_area :ans3 %>
  </div>
  <div class="field">
    <%= f.label :ans4 %><br>
    <%= f.text_area :ans4 %>
  </div>
  <div class="field">
    <%= f.label :correctAns %><br>
    <%= f.number_field :correctAns %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/javaquizzes/answering.html.erb
<h1 class='text-center'>Quiz on Java</h1>
<% @quizz.each do |a|%>
<b><%=h a.question%></b><br><br>
<p>
1.<%=h a.ans1%>
</p>
<p>
2.<%=h a.ans2%>
</p>
3.<%=h a.ans3%>
</p>
<p>
4.<%=h a.ans4%>
</p>
<%=form_tag(:action => "check", :id => a.id) do %>
<p>
The correct answer is number:
<%=text_field :ans ,params[:ans]%>
</p>
<p><%=submit_tag("Check", :class => 'btn btn-primary')%></p><br><br>
<%end%>
<%end%>

app/views/javaquizzes/edit.html.erb
<h1>Editing Javaquiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @javaquiz %> |
<%= link_to 'Back', javaquizzes_path %>

app/views/javaquizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Javaquizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Ans1</th>
      <th>Ans2</th>
      <th>Ans3</th>
      <th>Ans4</th>
      <th>Correctans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @javaquizzes.each do |javaquiz| %>
      <tr>
        <td><%= javaquiz.question %></td>
        <td><%= javaquiz.ans1 %></td>
        <td><%= javaquiz.ans2 %></td>
        <td><%= javaquiz.ans3 %></td>
        <td><%= javaquiz.ans4 %></td>
        <td><%= javaquiz.correctAns %></td>
        <td><%= link_to 'Show', javaquiz %></td>
        <td><%= link_to 'Edit', edit_javaquiz_path(javaquiz) %></td>
        <td><%= link_to 'Destroy', javaquiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Javaquiz', new_javaquiz_path %>

app/views/javaquizzes/new.html.erb
<h1>New Javaquiz</h1>

<%= render 'form' %>

<%= link_to 'Back', javaquizzes_path %>

app/views/javaquizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @javaquiz.question %>
</p>

<p>
  <strong>Ans1:</strong>
  <%= @javaquiz.ans1 %>
</p>

<p>
  <strong>Ans2:</strong>
  <%= @javaquiz.ans2 %>
</p>

<p>
  <strong>Ans3:</strong>
  <%= @javaquiz.ans3 %>
</p>

<p>
  <strong>Ans4:</strong>
  <%= @javaquiz.ans4 %>
</p>

<p>
  <strong>Correctans:</strong>
  <%= @javaquiz.correctAns %>
</p>

<%= link_to 'Edit', edit_javaquiz_path(@javaquiz) %> |
<%= link_to 'Back', javaquizzes_path %>